[project]
name = "h2-gae"
version = "0.1.0"
description = "Hierarchical & Heterogeneous Graph Autoencoder (H2-GAE)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx >=2.8",
    "osmnx >=2.0.3",
    "shapely >=2.1.0",
    "geopandas >0.12.0",
    "libpysal >=4.12.1",
    "momepy",
    "overturemaps",
]

[dependency-groups]
dev = [
    "ipython >=8.14.0",
    "jupyter >=1.0.0",
    "notebook >=7.0.0",
    "isort >=5.12.0",
    "ipykernel >=6.29.5",
    "matplotlib >=3.10.3",
    "folium >=0.19.6",
    "mapclassify >=2.8.1",
    "contextily>=1.6.2",
]